---
- name: Instalar Docker y Docker Compose
  hosts: ejercicio2
  become: yes
  tasks:
    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar docker
      apt:
        name: docker-compose
        state: present

    - name: Iniciar habilitar docker
      systemd:
        name: docker
        enabled: yes
        state: started

